### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by monte8902** [thesolarmoose/GGJ22-Duality#5]
1.	Cuando estás en la habitación principal de Andrea, el audio del aire se corta para volver a empezar.
2.	Los cables que quedan más arriba en el puzzle de soldar, se ve un pedazo afuera cuando están soldados
3.	Buscar sonido para cuando ya está soldado.
4.	Pantallas verdes desaparecen muy rápido (al menos a mi no me da tiempo de leer)
5.	“mañana será otro día. O no.” que el “O no” quede en la línea de abajo.
6.	La soldadura por debajo de la mano es normal??
7.	En el caso de las células de energía (en las pantallas en verde) debe ser “desconectadas”
8.	Cuando vas a interactuar con la caja del puzzle final, q la e salga de bajo pq Andrea la tapa
9.	La animación de la soldadura por debajo se ve fula cuando Andrea está en la mesa
10.	Que en la pantalla de créditos cuando presiones escape el juego se cierre

**Comment by mnicolas94** [comment]
Los enumeré pa poder comentarlos más fácil.
La 6 no la entiendo bien
Puedes elaborar en la 9? o es algo q en cuanto lo vea me daré cuenta?

**Comment by monte8902** [comment]
![soldadura](https://user-images.githubusercontent.com/85776217/151639000-db65b83d-0d70-4758-9986-8e0d7446b109.jpg)
esta talla q se ve por debajo. aquí en la interfaz de usuario me molesta pero no es el fin del mundo, pero eso mismo se ve en la escena final q andrea está soldando
