### ISSUE TITLE
bugs #7

### ISSUE THREAD

**Issue by monte8902** [thesolarmoose/GGJ22-Duality#7]
- Si interactuas con el televisor q despliega pantalla verde mientras la pantalla verde del inicio del día está activa, no muestra la otra (específicamente en el segundo día, en el tercer día sí cerró una y abrió la otra).
- Yo creo q debemos poner algún tipo de marca en la mano normal, en el puzzle de soldar, q indique donde dar clic pa coger el cable, pq se vuelve un poco tedioso y difícil estar dando el clic y se supone q esa sea la mano hábil.
- Poner efecto de sonido al resolverse el puzzle (la pregunta en el chat de telegram de la palanca es por esto, sino busco uno dif)
- ESTO NO ES UN BUG: qué tan complejo es q interactuar con el librero cambie el idioma del juego?

**Comment by mnicolas94** [comment]
los 3 últimos puntos ya los resolví, solo falta el 1ro que queda pal próximo update
